export const CartConst = {
    "SET_PRODUCT_TO_CART": "SET_PRODUCT_TO_CART",
    "REMOVE_PRODUCT_FROM_CART": "REMOVE_PRODUCT_FROM_CART",
    "CHANGE_PRODUCT_QUANTITY": "CHANGE_PRODUCT_QUANTITY",


} as const